# この課題の目的

- 数式演算ライブラリのnumpyに慣れる


- 機械学習に必須な行列演算に慣れる

# 課題１：内積を手計算する

以下のような行列A,Bに対して、行列の内積A＊Bを手計算で解きなさい。

$$
 \boldsymbol{A} = 
  \left[\begin{array}{cc}
       -1&2&3 \\
       4&-5&6 \\
       7&8&-9 \\
           \end{array}\right]           
$$

$$
 \boldsymbol{B} = 
  \left[\begin{array}{cc}
       0&2&1 \\
       0&2&-8 \\
       2&9&-1 \\
           \end{array}\right]           
$$



手計算の結果、行列の内積A＊Bは以下の通り求められた。

$$
\boldsymbol{A*B} = 
  \left[\begin{array}{cc}
    6   & 29 & -20 \\
    12  & 52 & 38\\
    -18 & -51& -48\\
      \end{array}\right]
$$

# 課題２：１次元配列の内積をfor文で計算する

課題１と同じ行列A,Bに対して、

- 行列Aの(0,0)の要素と行列Bの(0,1)の要素を掛け合わせる
- 行列Aの(0,1)の要素と行列Bの(1,1)の要素を掛け合わせる
- 行列Aの(0,2)の要素と行列Bの(2,1)の要素を掛け合わせる
- それらの値を全て足し合わせる

のフローをfor文を使って計算する。

In [3]:
# A*Bの(0,0)1を計算するコードを実装する

import numpy as np

# 行列を用意する
A = np.array([[-1 , 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1],[0 ,2, -8],[2, 9, -1]])

# 行列A＊Bの内積(inner_product)を格納する行列を作り、各成分を０で初期化する
inner_product = np.zeros((3,3)) 

#  A*Bの(0,0)を計算する
for i in range(3):
    inner_product[0][0] += A[0][i] * B[i][0]

#  計算結果を出力する
inner_product[0][0]

6.0

# 課題３：多次元配列の内積をfor文で計算する

課題１と同じ行列A,Bについて、行列の内積A * Bをfor文を使って計算する。

In [5]:
# 行列を用意する
A = np.array([[-1 , 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1],[0 ,2, -8],[2, 9, -1]])

# 行列A＊Bの内積(inner_product)を格納する行列を作り、各成分を０で初期化する
inner_product = np.zeros((3,3))

#  内積A*Bの(i,j)を計算する

for column in range(3): # 行インデックス
    for row in range(3): #  列インデックス
        for num in range(3): # 積和
            inner_product[column][row] += A[column][num] * B[num][row] # 出力はC[i][j]

#  計算結果を出力する
inner_product

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

### 上記は以下の計算をfor文を用いて実行している

```
inner_product_AB[0][0] += A[0][i] * B[i][0]
inner_product_AB[0][1] += A[0][i] * B[i][1]
inner_product_AB[0][2] += A[0][i] * B[i][2]

inner_product_AB[1][0] += A[1][i] * B[i][0]
inner_product_AB[1][1] += A[1][i] * B[i][1]
inner_product_AB[1][2] += A[1][i] * B[i][2]

inner_product_AB[2][0] += A[2][i] * B[i][0]
inner_product_AB[2][1] += A[2][i] * B[i][1]
inner_product_AB[2][2] += A[2][i] * B[i][2]
```

<考え方のコツ>
- 最初に出力であるinner_product[column][row]を書いておくと、計算で迷わなくなる。


- 行列Aは行インデックスを動かすので、for文の中では**"column"**と表現する。


- 行列Bは列インデックスを動かすので、for文の中では**"row"**と表現する。

# 課題４：内積をnp.dotで計算する

 - numpyのdotメソッドを用いて内積A* Bを計算する。

In [6]:
# 行列を用意する
A = np.array([[-1 , 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1],[0 ,2, -8],[2, 9, -1]])

# np.dotメソッドを用いて内積inner_product_AB = A*Bを計算する
inner_product_AB = np.dot(A, B)

#  計算結果を出力する
inner_product_AB

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 課題５：内積が計算できないときはどうするか？

以下のような行列A,Bに対して、行列の内積A＊Bはエラーが出て計算できない。

$$
 \boldsymbol{A} = 
  \left[\begin{array}{cc}
       -1&2&3 \\
       4&-5&6 \\
           \end{array}\right]           
$$

$$
 \boldsymbol{B} = 
  \left[\begin{array}{cc}
       9&8&7 \\
       6&-5&4 \\
           \end{array}\right]           
$$

- なぜエラーが出るのか理由を記載すること。

- 行列A, Bのいずれかに処理を施し、内積を計算すること。


### エラーが発生する理由 

 - 内積が計算できるためには、行列Aの列数と行列Bの列数が一致しなければならない。
 

 - 具体的には、行列Aがa × b行列、行列Bがb × c 行列の時、内積A * Bはa × c行列となる。 
 

 - 今回の例では行列Aが2×3行列、行列Bも2×3行列となっているため、内積が計算できない。
 
 
 - 内積を計算するためには行列Bを転置した転置行列$B^T$を求め、内積$A * B^T$を取れば良い。

### 内積を求める

In [8]:
# 行列を用意する
A = np.array([[-1 , 2, 3], [4, -5, 6]])
B = np.array([[9, 8, 7], [6 , -5, 4]])

# Bの転置行列B_Tを求める

B_T = B.T

# 内積inner_product_ABを計算する
inner_product_AB = np.dot(A, B_T)

# 結果を出力する
inner_product_AB

array([[28, -4],
       [38, 73]])

# Week2の課題を通じて得られた学び

以下に本課題を通じて得られた学びをまとめておきたい。

- 新しい概念が出てきた時は、まず小さく具体的にシンプルに、手を動かしながら考える。


- 手計算を何回かやってみることは重要。具体的な問題が解けると自信につながる。


- いきなり抽象的に考えると思考停止、苦手意識につながるので、やめること。


- 最初から細部にこだわることもやめる。まずは、全体像をざっくりつかむこと。


- 簡単なこと、具体的なことを少しずつ積み重ねるがポジティブな感情の維持につながる。


- 無意識に解けるレベルまで、具体的な問題を解くことを繰り返す。


- 繰り返す中で法則性、共通性を感じ取れるようになってきたら、少し抽象化してみる。


- 抽象化するとは、関数化できないか、繰り返し処理（for文、while文）できないか考える。


- 抽象化するときは、出力（return）→入力（前提条件・引数）→プロセスの順番でコーディングする。


- コーディングできたら、自分で具体的に解いた問題をコードを走らせてみる。


- コードを実行した結果が、自分が手計算で解いた結果と一致しているか確かめる。


- エラーメッセージが出ても気にしない。チャンスと捉えてエラーの内容を確認する。


- エラーを調べて、一つずつ紐解いていてコードを修正していく。


- 一旦、コードが完成したら、「もっとシンプルにできないか？」「他の人が見て分かりやすいか？」を考える。他の人の目線でレビューする。


- 「レビュー → 修正」を繰り返して保存する。
